---
Organizations:
  - &OrdererOrg
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: ./crypto-config/ordererOrganizations/divvy.com/msp
      Policies:
        Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
        Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
        Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"

# Capabilities:
#   Channel: &ChannelCapabilities
#     V1_4_2: true
#     V1_3: false
#     V1_1: false
#   Orderer: &OrdererCapabilities
#     V1_4_2: true
#     V1_1: false
#   Application: &ApplicationCapabilities
#     V1_4_2: true
#     V1_3: false
#     V1_2: false
#     V1_1: false

Application: &ApplicationDefaults
  Organizations:
  Policies: &ApplicationDefaultPolicies
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  # Capabilities:
  #     <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    orderer.divvy.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 500
    AbsoluteMaxBytes: 10 MB
    PreferredMaxBytes: 2 MB
  MaxChannels: 0
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  # Capabilities:
  #   <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  # Capabilities:
  #   <<: *ChannelCapabilities

Profiles:
  Genesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      # Capabilities:
      #   <<: *OrdererCapabilities
    Consortiums:
      Default:
        Organizations:
