OrdererOrgs:
  - Name: OrdererOrg
    Domain: divvy.com
    EnableNodeOUs: true
    # Only the first hostname is used in a Solo scenario.
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5
