version: '3.7'

networks:
  divvy:

services:
  ca.divvy.com:
    container_name: ca.divvy.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.divvy.com
    ports:
      - 7054:7054
    volumes:
      - ./crypto-config/peerOrganizations/:/etc/hyperledger/fabric-ca-server-config
      - ./ca.divvy.com/:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw --cafiles ca/org1/ca-config.yaml --cafiles ca/org2/ca-config.yaml'
    networks:
      - divvy

  orderer.divvy.com:
    container_name: orderer.divvy.com
    image: hyperledger/fabric-orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    environment:
      # Base configuration in ./config/orderer.yaml
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/production/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      # - ORDERER_GENERAL_TLS_ENABLED=true
      # - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      # - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      # - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
      # - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      # - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      # - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/production/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/divvy.com/orderers/orderer.divvy.com/msp/:/etc/hyperledger/msp/orderer/msp/
      - ./crypto-config/ordererOrganizations/divvy.com/orderers/orderer.divvy.com/tls/:/etc/hyperledger/msp/orderer/tls/
      - ./orderer.divvy.com/:/var/hyperledger/production/orderer
    command: orderer
    networks:
      - divvy

  peer.org1.divvy.com:
    container_name: peer.org1.divvy.com
    image: hyperledger/fabric-peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    environment:
      # Base configuration in ./config/core.yaml
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_divvy
      - FABRIC_LOGGING_SPEC=INFO
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer.org1.divvy.com
      - CORE_PEER_ADDRESS=peer.org1.divvy.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer.org1.divvy.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer.org1.divvy.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.org1.divvy.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config/peerOrganizations/org1.divvy.com/peers/peer.org1.divvy.com/msp/:/etc/hyperledger/fabric/msp
      # - ./crypto-config/peerOrganizations/org1.divvy.com/peers/peer.org1.divvy.com/tls/:/etc/hyperledger/fabric/tls
      - ./peer.org1.divvy.com/:/var/hyperledger/production
    command: peer node start
    networks:
      - divvy
